name: rtu_wimpillay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'  # CORREGIDO: Para Flutter debe ser este formato

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0  # CORREGIDO: Versión compatible con Flutter
  cloud_firestore: ^4.13.3  # CORREGIDO: Versión compatible con Flutter
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
