// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QEs-ULRR_lBkhK_kH6NrCBuo5gZIIKo',
    appId: '1:228454848747:web:a4430f8b39274182ca06ae',
    messagingSenderId: '228454848747',
    projectId: 'rtu-wimpillay',
    authDomain: 'rtu-wimpillay.firebaseapp.com',
    storageBucket: 'rtu-wimpillay.firebasestorage.app',
    measurementId: 'G-K7K8D8KG1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmDgWe70WCA5hqjKH4BjNmhrmhzCbG5FM',
    appId: '1:228454848747:android:ab4ed802c14745c9ca06ae',
    messagingSenderId: '228454848747',
    projectId: 'rtu-wimpillay',
    storageBucket: 'rtu-wimpillay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYxu5kJiXhlTijM168a61Hx2ydBE9qL_Y',
    appId: '1:228454848747:ios:8ef4348eb37039b9ca06ae',
    messagingSenderId: '228454848747',
    projectId: 'rtu-wimpillay',
    storageBucket: 'rtu-wimpillay.firebasestorage.app',
    iosBundleId: 'com.example.rtuWimpillay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYxu5kJiXhlTijM168a61Hx2ydBE9qL_Y',
    appId: '1:228454848747:ios:8ef4348eb37039b9ca06ae',
    messagingSenderId: '228454848747',
    projectId: 'rtu-wimpillay',
    storageBucket: 'rtu-wimpillay.firebasestorage.app',
    iosBundleId: 'com.example.rtuWimpillay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4QEs-ULRR_lBkhK_kH6NrCBuo5gZIIKo',
    appId: '1:228454848747:web:d962921dd5338298ca06ae',
    messagingSenderId: '228454848747',
    projectId: 'rtu-wimpillay',
    authDomain: 'rtu-wimpillay.firebaseapp.com',
    storageBucket: 'rtu-wimpillay.firebasestorage.app',
    measurementId: 'G-DVP25HJ8WW',
  );
}
